image: rust:1

variables:
  LLVM_SYS_170_FFI_WORKAROUND: "YES"

before_script:
  - apt-get update -qq && apt-get install -qq -y lsb-release software-properties-common
  - wget https://apt.llvm.org/llvm.sh
  - chmod +x llvm.sh
  # Workaround for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1043101
  - echo >> /etc/apt/sources.list
  - ./llvm.sh 17
  - apt-get install -qq -y libpolly-17-dev libzstd-dev

test:
  script:
    - cargo build
    - cargo test
    - cargo run --example nop-function
    - cargo run --example jit-function
    - echo "Hello, world!" | cargo run --example disassembler
  parallel:
    matrix:
      - RUNNER_TAG: ["", "aarch64"]
  tags:
    - "${RUNNER_TAG}"
