image: rust:1

variables:
  LLVM_SYS_191_FFI_WORKAROUND: "YES"
  # Commit in github.com/rust-lang/rust which corresponds to the newest LLVM.
  # Rust CI hosts tarballs with their LLVM builds, which are more up to date
  # than packages in distros where we can't use LLVM's nightly packages
  # (e.g. Alpine), which are usually one version behind.
  RUSTC_COMMIT: 41dd149fd6a6a06795fc6b9f54cb49af2f61775f

.build_definition:
  script: &default_build_script
    - cargo build
    - cargo test
    - cargo run --example nop-function
    - echo "Hello, world!" | cargo run --example disassembler

# Test on Alpine, using `unknown-linux-musl` LLVM tarball provided by Rust CI.
# The tarball is the same ones which Rust nightly uses.
#
# Unfortunately, Alpine doesn't package rc releases of LLVM and the stable
# versions usually land months after the release.
test:alpine-rustc-llvm-tarball:
  image: rust:alpine3.20
  variables:
    LLVM_SYS_191_PREFIX: /usr/lib/llvm-rustc
  before_script:
    # LLVM from Rust CI, even for the musl targets, is linked against libgcc_s
    # and libstdc++, not compiler-rt nor libc++.
    - apk update && apk add libffi-dev libgcc libstdc++-dev musl-dev
    - mkdir -p /usr/lib/llvm-rustc
    - |
      wget -q -O - "https://ci-artifacts.rust-lang.org/rustc-builds/${RUSTC_COMMIT}/rust-dev-nightly-x86_64-unknown-linux-musl.tar.xz" | \
      tar -xJ --strip-components 2 -C /usr/lib/llvm-rustc
  extends:
    - .build_definition

test:debian:
  image: rust:bookworm
  before_script:
    - apt-get update -qq && apt-get install -qq -y lsb-release software-properties-common
    - wget https://apt.llvm.org/llvm.sh
    - chmod +x llvm.sh
    # Workaround for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1043101
    - echo >> /etc/apt/sources.list
    - ./llvm.sh 19 all
  script:
    - *default_build_script
    # LLJIT uses `dlopen()` to open the shared libLLVM library. Therefore, we
    # run the JIT test only on environments where we link dynamically.
    - cargo run --example jit-function
  extends:
    - .build_definition

# Test cross-compilation to aarch64 on Debian, using `unknown-linux-gnu` LLVM
# tarball provided by Rust CI. The tarball is the same one which Rust nightly
# uses.
test:debian-rustc-llvm-tarball-cross-aarch64:
  image: rust:bookworm
  variables:
    LLVM_SYS_191_PREFIX: /usr/lib/llvm-rustc
    CARGO_BUILD_TARGET: aarch64-unknown-linux-gnu
  before_script:
    - dpkg --add-architecture arm64
    - |
      apt-get update -qq && apt-get install -qq -y \
        gcc-aarch64-linux-gnu \
        g++-aarch64-linux-gnu \
        libc6-dev-arm64-cross \
        libffi-dev:arm64 \
        libstdc++6:arm64 \
        qemu-user
    - rustup target add $CARGO_BUILD_TARGET
    - mkdir -p /usr/lib/llvm-rustc
    - |
      wget -q -O - "https://ci-artifacts.rust-lang.org/rustc-builds/${RUSTC_COMMIT}/rust-dev-nightly-${CARGO_BUILD_TARGET}.tar.xz" | \
      tar -xJ --strip-components 2 -C /usr/lib/llvm-rustc
  script:
    - *default_build_script
  extends:
    - .build_definition
