[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
# /usr/aarch64-linux-gnu is the default path of the LD prefix on Debian. It
# might be different on other distributions.
runner = "qemu-aarch64 -L /usr/lib/aarch64-linux-gnu"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-none-elf-gcc"
# /usr/aarch64-none-elf is the default path of the LD prefix on Alpine. It
# might be different on other distributions.
runner = "qemu-aarch64 -L /usr/aarch64-none-elf"

[target.riscv64gc-unknown-linux-gnu]
linker = "riscv64-linux-gnu-gcc"
# /usr/riscv64-linux-gnu is the default path of the LD prefix on Debian. It
# might be different on other distributions.
runner = "qemu-riscv64 -L /usr/lib/riscv64-linux-gnu"
